# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'MQTT Client Sample WS'

target 'MQTT Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT Client Sample
  pod 'AzureIoTUtility', '1.0.0-pre-release-1.0.8'
  pod 'AzureIoTuMqtt', '1.0.0-pre-release-1.0.8'
  pod 'AzureIoTuAmqp', '1.0.0-pre-release-1.0.8'
  pod 'AzureIoTHubClient', '1.0.0-pre-release-1.0.8'
end
